In [90]:
import numpy as np
import pandas as pd
from sklearn.svm import SVR
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

In [91]:
df = pd.read_csv("compositeData.csv")
df

fibre_length  basalt_fiber_content  curaua_fiber_content  tensile_strength
0              4                   100                     0             50.38
1              4                   100                     0             30.36
2              4                    75                    25             25.24
3              4                    75                    25             27.22
4              4                    75                    25             23.01
5              4                    50                    50             23.71
6              4                    50                    50             26.87
7              4                    50                    50             22.89
8              4                    25                    75             32.67
9              4                    25                    75             32.11
10             4                    25                    75             29.97
11             4                    25                    75             27.70
12             4                     0                   100             10.54
13             4                     0                   100             17.20
14             4                     0                   100             13.00
15             8                   100                     0             35.52
16             8                   100                     0             41.84
17             8                   100                     0             24.00
18             8                   100                     0             21.03
19             8                   100                     0             28.82
20             8                    75                    25             39.14
21             8                    75                    25             32.60
22             8                    75                    25             31.30
23             8                    50                    50             25.39
24             8                    50                    50             31.10
25             8                    50                    50             29.02
26             8                    50                    50             29.52
27             8                    50                    50             38.65
28             8                    25                    75             26.75
29             8                    25                    75             21.57
30             8                    25                    75             27.98
31             8                    25                    75             24.14
32             8                     0                   100             20.91
33             8                     0                   100             28.80
34            12                   100                     0             31.49
35            12                   100                     0             27.87
36            12                   100                     0             21.42
37            12                    75                    25             24.43
38            12                    50                    50             25.65
39            12                    50                    50             21.26
40            12                    25                    75             21.15
41            12                     0                   100             33.67
42            12                     0                   100             36.83
43            12                     0                   100             34.40
44            12                     0                   100             36.36

In [92]:
df.describe()

fibre_length  basalt_fiber_content  curaua_fiber_content  \
count     45.000000              45.00000              45.00000   
mean       7.644444              50.00000              50.00000   
std        3.053728              36.14994              36.14994   
min        4.000000               0.00000               0.00000   
25%        4.000000              25.00000              25.00000   
50%        8.000000              50.00000              50.00000   
75%        8.000000              75.00000              75.00000   
max       12.000000             100.00000             100.00000   

       tensile_strength  
count         45.000000  
mean          28.121778  
std            7.342803  
min           10.540000  
25%           23.710000  
50%           27.870000  
75%           32.110000  
max           50.380000

In [93]:
dataStuff = df[['fibre_length', 'basalt_fiber_content', 'curaua_fiber_content']]
targetStuff = df['tensile_strength']

In [94]:
xTrain, xTest, yTrain, yTest = train_test_split(dataStuff, targetStuff, test_size=0.2, random_state=42)

# LinearReg Model

In [95]:
modelLR = LinearRegression()
modelLR.fit(xTrain, yTrain)

LinearRegression()

In [96]:
yPred = modelLR.predict(xTest)
yPred

array([28.897658  , 28.33219196, 28.33219196, 25.7034481 , 32.0918679 ,
       25.7034481 , 29.36383086, 24.57251602, 26.16962096])

In [97]:
print("Root Mean Square Error: ", np.sqrt(mean_squared_error(yTest, yPred)))
print('Mean Squared Error:', mean_squared_error(yTest, yPred))
print('R-squared:', r2_score(yTest, yPred))

Root Mean Square Error:  7.428739387933987
Mean Squared Error: 55.18616889384183
R-squared: -0.07443982552013684


# PolyReg Model

In [98]:
for i in range(1, 25):
    polyReg = PolynomialFeatures(degree=i)
    linReg = LinearRegression()
    modelPR = Pipeline([('poly', polyReg), ('linear', linReg)])
    modelPR.fit(xTrain, yTrain)
    yPred = modelPR.predict(xTest)
    print("Poly Features Degree: ", i)
    print("Root Mean Square Error: ", np.sqrt(mean_squared_error(yTest, yPred)))
    print('Mean Squared Error:', mean_squared_error(yTest, yPred))
    print('R-squared:', r2_score(yTest, yPred))
    print("\n")

Poly Features Degree:  1
Root Mean Square Error:  7.428739387933987
Mean Squared Error: 55.18616889384184
R-squared: -0.07443982552013706


Poly Features Degree:  2
Root Mean Square Error:  5.839834276191594
Mean Squared Error: 34.103664373382195
R-squared: 0.3360232113698519


Poly Features Degree:  3
Root Mean Square Error:  5.165081620354048
Mean Squared Error: 26.678068144919198
R-squared: 0.48059487626364494


Poly Features Degree:  4
Root Mean Square Error:  3.401164116669847
Mean Squared Error: 11.567917348522581
R-squared: 0.7747799612347269


Poly Features Degree:  5
Root Mean Square Error:  3.085003502151584
Mean Squared Error: 9.517246608287536
R-squared: 0.8147052243305541


Poly Features Degree:  6
Root Mean Square Error:  3.080414985270776
Mean Squared Error: 9.488956481480754
R-squared: 0.8152560152174644


Poly Features Degree:  7
Root Mean Square Error:  3.0804149852710814
Mean Squared Error: 9.488956481482637
R-squared: 0.8152560152174277


Poly Features Degree:  8
Ro

# DecisionTreeReg Model

In [99]:
modelDT = DecisionTreeRegressor(random_state=42)
modelDT.fit(xTrain, yTrain)

DecisionTreeRegressor(random_state=42)

In [100]:
yPred = modelDT.predict(xTest)
yPred

array([25.65      , 31.71333333, 31.71333333, 36.595     , 26.455     ,
       36.595     , 26.23      , 15.1       , 29.92666667])

In [101]:
print("Root Mean Square Error: ", np.sqrt(mean_squared_error(yTest, yPred)))
print('Mean Squared Error:', mean_squared_error(yTest, yPred))
print('R-squared:', r2_score(yTest, yPred))

Root Mean Square Error:  3.0804149852708935
Mean Squared Error: 9.488956481481479
R-squared: 0.8152560152174503


# RandomForestReg Model

In [102]:
modelRF = RandomForestRegressor(n_estimators=100, random_state=42)
modelRF.fit(xTrain, yTrain)

RandomForestRegressor(random_state=42)

In [103]:
yPred = modelRF.predict(xTest)
yPred

array([26.10417833, 31.77278   , 31.77278   , 34.95426333, 26.46847   ,
       34.95426333, 27.30111333, 17.13378333, 29.51219016])

In [104]:
print("Root Mean Square Error: ", np.sqrt(mean_squared_error(yTest, yPred)))
print('Mean Squared Error:', mean_squared_error(yTest, yPred))
print('R-squared:', r2_score(yTest, yPred))

Root Mean Square Error:  3.5261420680230153
Mean Squared Error: 12.433677883881629
R-squared: 0.7579241508532747


# SupportVectorReg Model

In [105]:
modelSVR = SVR()
modelSVR.fit(xTrain, yTrain)

SVR()

In [106]:
yPred = modelSVR.predict(xTest)
yPred

array([26.7507989 , 26.75582383, 26.75582383, 27.46050291, 28.90469784,
       27.46050291, 27.84853127, 27.43874895, 26.85897323])

In [107]:
print("Root Mean Square Error: ", np.sqrt(mean_squared_error(yTest, yPred)))
print('Mean Squared Error:', mean_squared_error(yTest, yPred))
print('R-squared:', r2_score(yTest, yPred))

Root Mean Square Error:  7.252955284034097
Mean Squared Error: 52.60536035219812
R-squared: -0.02419311452777473


# GradBoostingReg Model

In [108]:
modelGBR = GradientBoostingRegressor(random_state=42)
modelGBR.fit(xTrain, yTrain)

GradientBoostingRegressor(random_state=42)

In [109]:
yPred = modelGBR.predict(xTest)
yPred

array([25.71181741, 31.54740627, 31.54740627, 36.49305978, 26.45297316,
       36.49305978, 26.75196409, 15.44766411, 29.39415521])

In [110]:
print("Root Mean Square Error: ", np.sqrt(mean_squared_error(yTest, yPred)))
print('Mean Squared Error:', mean_squared_error(yTest, yPred))
print('R-squared:', r2_score(yTest, yPred))

Root Mean Square Error:  3.2230763249268324
Mean Squared Error: 10.388220996303856
R-squared: 0.7977479035335094
